swagger: '2.0'
info:
  version: v1
  title: REST API Documentation for the MOTI School Bus Application
  description: The School Bus application tracks that inspections are performed in a timely fashion. For each school bus the application tracks information about the bus (including data from ICBC, NSC, etc.), it's past and next inspection dates and results, contacts, and the inspector responsible for next inspecting the bus.
  termsOfService: N/A
basePath: /api
paths:
